CS123/urls.py
from django.contrib import admin
from django.urls import include, path




urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('websites.urls')),
]

websites/urls.py
from django.urls import path

from . import views



'''app_name = 'polls'
urlpatterns = [
	# ex: /polls/
	path('', views.index, name='index'),
	# ex: /polls/5/
	path('<int:question_id>/', views.detail, name='detail'),
	# ex: /polls/5/results/
	path('<int:question_id>/results/', views.results, name='results'),
	# ex: /polls/5/vote/
	path('<int:question_id>/vote/', views.vote, name='vote'),
]'''


app_name = 'websites'
urlpatterns = [
	path('',views.Homepage, name='Homepage'),
	path('login/',views.loginattempt, name='loginattempt'),
	path('login/#',views.login, name='login'),
	path('directory/',views.directory, name='directory'),
	path('calendar/',views.events, name='events'),
	path('editpage/',views.editpage, name='editpage'),
	path('edit/',views.edit, name='edit'),
	path('schedule/',views.adddate, name='adddate'),
	path('schedule/#',views.insertdate, name='insertdate'),
	path('newmember/',views.newmember, name='newmember'),
	path('newmember/#',views.insertmember, name='insertmember'),
	path('customize/#',views.customize, name='customize')
]

websites/models.py
import datetime
from django.core.validators import RegexValidator
from django.db import connection, models
from django.utils import timezone

# Create your models here.
class user(models.Model):
	u_username=models.CharField(max_length=255,primary_key=True)
	u_password=models.CharField(max_length=255)
	u_varsity=models.IntegerField(null=True)
	def __int__(self):
		return u_username
	
class varsity(models.Model):
	v_num=models.IntegerField(primary_key=True)
	v_name=models.CharField(max_length=255)
	v_email=models.CharField(max_length=255,null=True)
	v_contact=models.CharField(max_length=255,null=True)
	def __int__(self):
		return v_num
	
class member(models.Model):
	m_team=models.ForeignKey(varsity, on_delete = models.CASCADE, related_name='members')
	m_name=models.CharField(max_length=255)
	m_role=models.CharField(max_length=255)
	
class eventlol(models.Model):
	e_team=models.ForeignKey(varsity, on_delete = models.CASCADE, related_name='dates')
	e_date=models.CharField(max_length=255,null=True)
	e_start=models.CharField(max_length=255,null=True)
	e_end=models.CharField(max_length=255,null=True)
	e_desc=models.CharField(max_length=255,null=True)
	#e_date=models.DateField(null=True, blank=True)
	#e_start=models.TimeField(null=True, blank=True)
	#e_end=models.TimeField(null=True, blank=True)
	#blahblah testing how to use github

websites/views.py
from django.http import HttpResponse
from django.template import loader
from django.http import Http404
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
import datetime
from django.utils import timezone
from django.shortcuts import redirect
from django.db.models.query import EmptyQuerySet
from django.template.loader import render_to_string
from .models import user, member, varsity, eventlol

def usercount():
    no = user.objects.count()
    return no + 1
	
def membercount():
    no = member.objects.count()
    return no + 1
	
def	eventcount():
	no=eventlol.objects.count()
	return no+1

def Homepage(request):
	vars=request.session['vnum']
	context = {'vnum': vars}
	return render(request,'websites/Homepage.html')
	
def loginattempt (request):
	return render(request, 'websites/login-screen/login.html')
	
def login (request):
	if (isinstance(request.POST['username'], str) and request.POST['username']!= '' and isinstance(request.POST['password'],str)and request.POST['password']!=''):
		curuser=user.objects.filter(u_username=request.POST['username']).filter(u_password=request.POST['password'])
		print(user.objects.none() )
		if (  len(curuser)==0 ):
			return render(request,'websites/login-screen/login.html', {'error_message': "Invalid Credentials."})
		else:
			if(curuser.first().u_varsity==None):
				return redirect('websites:Homepage')
			else:
				request.session['vnum']=curuser.first().u_varsity
				return  redirect('websites:customize')
	else:
		return render(request,'websites/login-screen/login.html', {'error_message': "Invalid Credentials."})
		
def editpage(request):
	return render(request,'websites/editpage.html')
	
def edit(request):
	vars=varsity.objects.get(v_num=request.session['vnum'])
	if (isinstance(request.POST['name'], str) and request.POST['name']!= ''):
		vars.v_name=request.POST['name']
	if( isinstance(request.POST['email'],str)and request.POST['email']!=''):
		vars.v_email=request.POST['email']
	if( isinstance(request.POST['contact'],str)and request.POST['contact']!=''):
		vars.v_contact=request.POST['contact']
	vars.save()
	return redirect('websites:Homepage')
	
def directory (request):
	varsities=varsity.objects.all()
	if request.method=='POST':
		if isinstance(request.POST['varsityname'],str) and request.POST['varsityname']!='':
			varsities=varsities.filter(v_name__icontains=request.POST['varsityname'])
	members=member.objects.all()
	context = {'varsities': varsities,'members': members}
	return render(request, 'websites/directory.html', context)

def events (request):
	dates = eventlol.objects.all()
	context = {'dates': dates}
	return render(request, 'websites/events.html', context)

def adddate(request):
	return render(request,'websites/adddate.html')
	
def insertdate(request):
	vars=varsity.objects.get(v_num=request.session['vnum'])
	new =eventlol(
	e_team=vars,
	e_date=request.POST['date'],
	e_start=request.POST['start'],
	e_end=request.POST['end'],
	)
	new.save()
	return redirect('websites:Homepage')
	
def insertmember(request):
	new= member(
		m_team=varsity.objects.get(v_num=request.session['vnum']),
		m_name=request.POST['name'],
		m_role=request.POST['role'],
	)
	new.save()
	return redirect('websites:Homepage')
	
def newmember(request):
	return render(request,'websites/newmember.html')
	
def customize(request):
	return render(request,'websites/customize.html')
	
#from datetime import datetime
#datetime_object = datetime.strptime('Jun 1 2005  1:33PM', '%b %d %Y %I:%M%p')

websites/templates/websites/Homepage.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Homepage</title>
</head>
<body >
				<div>
					<a href="{% url 'websites:Homepage' %}">Home</a>
				</div>
				<div >
					<a href="{% url 'websites:events' %}">Calendar</a>
				</div>
				<div >
					<a href="{% url 'websites:directory' %}">Directory</a>
				</div>
				<div >
					<a >About Us</a>
				</div>
				<div >
					<a >Contact Us</a>
				</div>
				{%for item in vnum %}
				<div >
					<a href="{% url 'websites:adddate' %}" >Contact Us</a>
				</div>
				{% endfor %}
				<div >
					<a href="{% url 'websites:loginattempt' %}" >Get Started</a>
				</div>
</body>
</html>

websites/templates/websites/adddate.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Homepage</title>
</head>
<body >
				<div>
					<a href="{% url 'websites:Homepage' %}">Home</a>
				</div>
				<div >
					<a href="{% url 'websites:events' %}">Calendar</a>
				</div>
				<div >
					<a href="{% url 'websites:directory' %}">Directory</a>
				</div>
				<div >
					<a >About Us</a>
				</div>
				<div >
					<a >Contact Us</a>
				</div>
				
				<form action="{% url 'websites:insertdate' %}" method="post">
				{% csrf_token %}
				<div class="input-field">
		            <span >Date</span>
		            <input name="date" type="text">
		        </div> 
				<div class="input-field">
		            <span >Start</span>
		            <input  name="start" type="text">
		        </div> 
				<div class="input-field">
		            <span >End</span>
		            <input  name="end" type="text">
		        </div> 
				<button c type="submit" name="action" value="login">Submit</button>
				</form>
				
				
</body>
</html>

websites/templates/websites/customize.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Homepage</title>
</head>
<body >
				<div>
					<a href="{% url 'websites:Homepage' %}">Home</a>
				</div>
				<div >
					<a href="{% url 'websites:events' %}">Calendar</a>
				</div>
				<div >
					<a href="{% url 'websites:directory' %}">Directory</a>
				</div>
				<div >
					<a >About Us</a>
				</div>
				<div >
					<a >Contact Us</a>
				</div>
				
				<form action="{% url 'websites:editpage' %}" method="post">
				{% csrf_token %}
				<button c type="submit" name="action" value="editpage">Edit Varsity Info</button>
				</form>
				<form action="{% url 'websites:newmember' %}" method="post">
				{% csrf_token %}
				<button c type="submit" name="action" value="newmember">Add Member</button>
				</form>
				<form action="{% url 'websites:adddate' %}" method="post">
				{% csrf_token %}
				<button c type="submit" name="action" value="adddate">Add Event</button>
				</form>
				
				
</body>
</html>

websites/templates/websites/directory.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Homepage</title>
</head>
<body >
	<div>
					<a href="{% url 'websites:Homepage' %}">Home</a>
				</div>
				<div >
					<a href="{% url 'websites:events' %}">Calendar</a>
				</div>
				<div >
					<a href="{% url 'websites:directory' %}">Directory</a>
				</div>
				<div >
					<a >About Us</a>
				</div>
				<div >
					<a >Contact Us</a>
				</div>
					<form action="{% url 'websites:directory' %}" method="post">
						{% csrf_token %}
						<div class="input-field">
							<input id="varsityname" name="varsityname" type="text" class="validate">
							<label class="black-text" for="varsityname">Varsity Name</label>
						</div>

						<button type="submit" name="action">Search</button>
					</form>
		
						<div>
							<table >
								<thead>
									<tr>
										<th>Varsity</th>
										<th>Email</th>
										<th>Contact #</th>
									</tr>
								<thead>
								<tbody>
									{% for item in varsities %}
										<tr>
											<th>{{item.v_name}}</th>
											<th>{{item.v_email}}</th>
											<th>{{item.v_contact}}</th>
												<table >
													<thead>
													<tr>
													<th>Name</th>
													<th>Role</th>
													</tr>
													<thead>
											{%for member in members %}
												{% if member.m_team == item %}
													<tbody>
													<th>{{member.m_name}}</th>
													<th>{{member.m_role}}</th>
													</tbody>
												{% endif %}
												<table >
											{% endfor %}
										</tr>
									{% endfor %}
								</tbody>
							</table >
						</div>

</body>
</html>

websites/templates/websites/editpage.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Homepage</title>
</head>
<body >
				<div>
					<a href="{% url 'websites:Homepage' %}">Home</a>
				</div>
				<div >
					<a href="{% url 'websites:events' %}">Calendar</a>
				</div>
				<div >
					<a href="{% url 'websites:directory' %}">Directory</a>
				</div>
				<div >
					<a >About Us</a>
				</div>
				<div >
					<a >Contact Us</a>
				</div>
				
				<form action="{% url 'websites:edit' %}" method="post">
				{% csrf_token %}
				<name="varsity"> 
				<div class="input-field">
		            <span >Varsity Name</span>
		            <input name="name" type="text">
		        </div> 
				<div class="input-field">
		            <span >Email Address</span>
		            <input  name="email" type="text">
		        </div> 
				<div class="input-field">
		            <span >Contact Information</span>
		            <input  name="contact" type="text">
		        </div> 
				<button c type="submit" name="action" value="edit">Submit</button>
				</form>
				
				
</body>
</html>

websites/templates/websites/events.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Homepage</title>
</head>
<body >
				<div>
					<a href="{% url 'websites:Homepage' %}">Home</a>
				</div>
				<div >
					<a href="{% url 'websites:events' %}">Calendar</a>
				</div>
				<div >
					<a href="{% url 'websites:directory' %}">Directory</a>
				</div>
				<div >
					<a >About Us</a>
				</div>
				<div >
					<a >Contact Us</a>
				</div>
		
						<div>
							<table >
								<thead>
									<tr>
										<th>Varsity</th>
										<th>Date</th>
										<th>Start</th>
										<th>End</th>
									</tr>
								<thead>
								<tbody>
									{% for item in dates %}
										<tr>
											<th>{{item.e_team.v_name}}</th>
											<th>{{item.e_date}}</th>
											<th>{{item.e_start}}</th>
											<th>{{item.e_end}}</th>
										</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>

</body>
</html>

websites/templates/websites/newmember.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Homepage</title>
</head>
<body >
				<div>
					<a href="{% url 'websites:Homepage' %}">Home</a>
				</div>
				<div >
					<a href="{% url 'websites:events' %}">Calendar</a>
				</div>
				<div >
					<a href="{% url 'websites:directory' %}">Directory</a>
				</div>
				<div >
					<a >About Us</a>
				</div>
				<div >
					<a >Contact Us</a>
				</div>
				
				<form action="{% url 'websites:insertmember' %}" method="post">
				{% csrf_token %}
				<div class="input-field">
		            <span >Name</span>
		            <input  name="name" type="text">
		        </div> 	
				<div class="input-field">
		            <span >Role</span>
		            <input  name="role" type="text">
		        </div> 
				<button c type="submit" name="action" value="login">Submit</button>
				</form>
				
				
</body>
</html>